# Generated by Django 5.2.17 on 2026-10-03 14:12

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("issue_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
            options={
                "ordering": ["title", "issue_number"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "comics",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="catalog.comic"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="catalog.publisher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "series",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="comic",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comics",
                to="catalog.series",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("author", models.CharField(max_length=120)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "comic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.comic",
                    ),
                ),
            ],
            options={
                "ordering": ["author"],
                "constraints": [
                    models.UniqueConstraint(fields=("comic", "author"), name="unique_comic_author"),
                    models.CheckConstraint(
                        condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                        name="review_rating_1_to_5",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="series",
            constraint=models.UniqueConstraint(
                fields=("publisher", "title"), name="unique_publisher_series"
            ),
        ),
        migrations.AddConstraint(
            model_name="comic",
            constraint=models.UniqueConstraint(
                fields=("series", "issue_number"), name="unique_series_issue"
            ),
        ),
        migrations.AddConstraint(
            model_name="comic",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gt", 0)), name="comic_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="comic",
            constraint=models.CheckConstraint(
                condition=models.Q(("pages__gt", 0)), name="comic_pages_positive"
            ),
        ),
    ]
